//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Titan.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Titan.Domain.Properties.Resources - Copy", typeof(Resources___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active .
        /// </summary>
        internal static string Active_ {
            get {
                return ResourceManager.GetString("Active ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted .
        /// </summary>
        internal static string Deleted_ {
            get {
                return ResourceManager.GetString("Deleted ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired .
        /// </summary>
        internal static string Expired_ {
            get {
                return ResourceManager.GetString("Expired ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpiresAt .
        /// </summary>
        internal static string ExpiresAt_ {
            get {
                return ResourceManager.GetString("ExpiresAt ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive .
        /// </summary>
        internal static string Inactive_ {
            get {
                return ResourceManager.GetString("Inactive ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked .
        /// </summary>
        internal static string Locked_ {
            get {
                return ResourceManager.GetString("Locked ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending .
        /// </summary>
        internal static string Pending_ {
            get {
                return ResourceManager.GetString("Pending ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended .
        /// </summary>
        internal static string Suspended_ {
            get {
                return ResourceManager.GetString("Suspended ", resourceCulture);
            }
        }
    }
}
