//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Titan.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Titan.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation key cannot be empty..
        /// </summary>
        internal static string ActivationKey_Empty {
            get {
                return ResourceManager.GetString("ActivationKey_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action cannot be null or empty..
        /// </summary>
        internal static string ActivityLog_ActionEmpty {
            get {
                return ResourceManager.GetString("ActivityLog_ActionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID cannot be empty..
        /// </summary>
        internal static string ActivityLog_UserIdEmpty {
            get {
                return ResourceManager.GetString("ActivityLog_UserIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City cannot be empty..
        /// </summary>
        internal static string Address_CityEmpty {
            get {
                return ResourceManager.GetString("Address_CityEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country cannot be empty..
        /// </summary>
        internal static string Address_CountryEmpty {
            get {
                return ResourceManager.GetString("Address_CountryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number cannot be empty..
        /// </summary>
        internal static string Address_NumberEmpty {
            get {
                return ResourceManager.GetString("Address_NumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State cannot be empty..
        /// </summary>
        internal static string Address_StateEmpty {
            get {
                return ResourceManager.GetString("Address_StateEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street cannot be empty..
        /// </summary>
        internal static string Address_StreetEmpty {
            get {
                return ResourceManager.GetString("Address_StreetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code cannot be empty..
        /// </summary>
        internal static string Address_ZipEmpty {
            get {
                return ResourceManager.GetString("Address_ZipEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name cannot be null or empty..
        /// </summary>
        internal static string Company_Empty {
            get {
                return ResourceManager.GetString("Company_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name cannot be null or empty..
        /// </summary>
        internal static string CompanyUser_Empty {
            get {
                return ResourceManager.GetString("CompanyUser_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composite role name cannot be empty..
        /// </summary>
        internal static string CompositeRoleName_CompositeRoleEmpty {
            get {
                return ResourceManager.GetString("CompositeRoleName_CompositeRoleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role intersection resulted in empty set..
        /// </summary>
        internal static string CompositeRoleName_Intersect {
            get {
                return ResourceManager.GetString("CompositeRoleName_Intersect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remove the last role from a composite role..
        /// </summary>
        internal static string CompositeRoleName_Remove {
            get {
                return ResourceManager.GetString("CompositeRoleName_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one role name must be provided..
        /// </summary>
        internal static string CompositeRoleName_RoleEmpty {
            get {
                return ResourceManager.GetString("CompositeRoleName_RoleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name cannot be empty..
        /// </summary>
        internal static string CompositeRoleName_RoleName {
            get {
                return ResourceManager.GetString("CompositeRoleName_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add currencies with different codes:.
        /// </summary>
        internal static string Currency_Add {
            get {
                return ResourceManager.GetString("Currency_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string Currency_And {
            get {
                return ResourceManager.GetString("Currency_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot divide by zero..
        /// </summary>
        internal static string Currency_Divide {
            get {
                return ResourceManager.GetString("Currency_Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency code cannot be empty..
        /// </summary>
        internal static string Currency_Empty {
            get {
                return ResourceManager.GetString("Currency_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid monetary value..
        /// </summary>
        internal static string Currency_InvalidValue {
            get {
                return ResourceManager.GetString("Currency_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot subtract currencies with different codes:.
        /// </summary>
        internal static string Currency_Subtract {
            get {
                return ResourceManager.GetString("Currency_Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be empty..
        /// </summary>
        internal static string Currency_ValueEmpty {
            get {
                return ResourceManager.GetString("Currency_ValueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days cannot be negative..
        /// </summary>
        internal static string DateRange_DaysNotNegative {
            get {
                return ResourceManager.GetString("DateRange_DaysNotNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be equal to or greater than start date..
        /// </summary>
        internal static string DateRange_GreaterThan {
            get {
                return ResourceManager.GetString("DateRange_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot intersect non-overlapping date ranges..
        /// </summary>
        internal static string DateRange_Intersect {
            get {
                return ResourceManager.GetString("DateRange_Intersect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration cannot be negative..
        /// </summary>
        internal static string DateRange_Negative {
            get {
                return ResourceManager.GetString("DateRange_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval must be positive..
        /// </summary>
        internal static string DateRange_Split {
            get {
                return ResourceManager.GetString("DateRange_Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot union non-overlapping date ranges..
        /// </summary>
        internal static string DateRange_Union {
            get {
                return ResourceManager.GetString("DateRange_Union", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain must contain at least one period..
        /// </summary>
        internal static string DomainName_EmptyPeriod {
            get {
                return ResourceManager.GetString("DomainName_EmptyPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain is too long..
        /// </summary>
        internal static string DomainName_TooLong {
            get {
                return ResourceManager.GetString("DomainName_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be null or empty..
        /// </summary>
        internal static string Email_Empty {
            get {
                return ResourceManager.GetString("Email_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid..
        /// </summary>
        internal static string Email_Invalid {
            get {
                return ResourceManager.GetString("Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is too long..
        /// </summary>
        internal static string Email_TooLong {
            get {
                return ResourceManager.GetString("Email_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID cannot be empty..
        /// </summary>
        internal static string EmployeeId_Empty {
            get {
                return ResourceManager.GetString("EmployeeId_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID is too long..
        /// </summary>
        internal static string EmployeeId_TooLong {
            get {
                return ResourceManager.GetString("EmployeeId_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbreviation cannot be empty..
        /// </summary>
        internal static string JobTitle_AbbreviationNegative {
            get {
                return ResourceManager.GetString("JobTitle_AbbreviationNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department cannot be empty..
        /// </summary>
        internal static string JobTitle_DepartmentEmpty {
            get {
                return ResourceManager.GetString("JobTitle_DepartmentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title cannot be empty..
        /// </summary>
        internal static string JobTitle_Empty {
            get {
                return ResourceManager.GetString("JobTitle_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level cannot be negative..
        /// </summary>
        internal static string JobTitle_LevelNegative {
            get {
                return ResourceManager.GetString("JobTitle_LevelNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown job title abbreviation:.
        /// </summary>
        internal static string JobTitle_UnknownAbbreviation {
            get {
                return ResourceManager.GetString("JobTitle_UnknownAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be null or empty..
        /// </summary>
        internal static string Name_Empty {
            get {
                return ResourceManager.GetString("Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is too long..
        /// </summary>
        internal static string Name_TooLong {
            get {
                return ResourceManager.GetString("Name_TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty..
        /// </summary>
        internal static string PasswordHash_Empty {
            get {
                return ResourceManager.GetString("PasswordHash_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash value cannot be empty..
        /// </summary>
        internal static string PasswordHash_HashEmpty {
            get {
                return ResourceManager.GetString("PasswordHash_HashEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be null or empty..
        /// </summary>
        internal static string PersonUser_NameEmpty {
            get {
                return ResourceManager.GetString("PersonUser_NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number cannot be empty..
        /// </summary>
        internal static string PhoneNumber_Empty {
            get {
                return ResourceManager.GetString("PhoneNumber_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid international phone number format..
        /// </summary>
        internal static string PhoneNumber_InternationalNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumber_InternationalNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number format..
        /// </summary>
        internal static string PhoneNumber_NationalNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumber_NationalNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert to E.164 format without country code..
        /// </summary>
        internal static string PhoneNumber_ToE164Format {
            get {
                return ResourceManager.GetString("PhoneNumber_ToE164Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name cannot be null or empty..
        /// </summary>
        internal static string Role_Empty {
            get {
                return ResourceManager.GetString("Role_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        internal static string SocialMediaProvider_Facebook {
            get {
                return ResourceManager.GetString("SocialMediaProvider_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        internal static string SocialMediaProvider_Google {
            get {
                return ResourceManager.GetString("SocialMediaProvider_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.
        /// </summary>
        internal static string SocialMediaProvider_Microsoft {
            get {
                return ResourceManager.GetString("SocialMediaProvider_Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported social media provider:.
        /// </summary>
        internal static string SocialMediaProvider_UnsupportedProvider {
            get {
                return ResourceManager.GetString("SocialMediaProvider_UnsupportedProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID cannot be null or empty..
        /// </summary>
        internal static string StaffUser_EmployeeIdEmpty {
            get {
                return ResourceManager.GetString("StaffUser_EmployeeIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name cannot be null or empty..
        /// </summary>
        internal static string StaffUser_NameEmpty {
            get {
                return ResourceManager.GetString("StaffUser_NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Number cannot be empty..
        /// </summary>
        internal static string TaxNumber_Empty {
            get {
                return ResourceManager.GetString("TaxNumber_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be null or empty..
        /// </summary>
        internal static string UserBase_EmailEmpty {
            get {
                return ResourceManager.GetString("UserBase_EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role cannot be null or empty..
        /// </summary>
        internal static string UserBase_RoleEmpty {
            get {
                return ResourceManager.GetString("UserBase_RoleEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string UserStatus_Active {
            get {
                return ResourceManager.GetString("UserStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason is required for deleted status..
        /// </summary>
        internal static string UserStatus_CreateDeleted {
            get {
                return ResourceManager.GetString("UserStatus_CreateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason is required for locked status..
        /// </summary>
        internal static string UserStatus_CreateLocked {
            get {
                return ResourceManager.GetString("UserStatus_CreateLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason is required for suspended status..
        /// </summary>
        internal static string UserStatus_CreateSuspended {
            get {
                return ResourceManager.GetString("UserStatus_CreateSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string UserStatus_Deleted {
            get {
                return ResourceManager.GetString("UserStatus_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        internal static string UserStatus_Expired {
            get {
                return ResourceManager.GetString("UserStatus_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires at.
        /// </summary>
        internal static string UserStatus_ExpiresAt {
            get {
                return ResourceManager.GetString("UserStatus_ExpiresAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string UserStatus_Inactive {
            get {
                return ResourceManager.GetString("UserStatus_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        internal static string UserStatus_Locked {
            get {
                return ResourceManager.GetString("UserStatus_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string UserStatus_Pending {
            get {
                return ResourceManager.GetString("UserStatus_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        internal static string UserStatus_Suspended {
            get {
                return ResourceManager.GetString("UserStatus_Suspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown status type:.
        /// </summary>
        internal static string UserStatus_Unknown {
            get {
                return ResourceManager.GetString("UserStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration date must be in the future..
        /// </summary>
        internal static string UserStatus_WithExpiration {
            get {
                return ResourceManager.GetString("UserStatus_WithExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason cannot be empty..
        /// </summary>
        internal static string UserStatus_WithReason {
            get {
                return ResourceManager.GetString("UserStatus_WithReason", resourceCulture);
            }
        }
    }
}
